name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
    linux:
        strategy:
            fail-fast: false
            matrix:
                include:
                  - { os: ubuntu-22.04 }
                  - { os: ubuntu-20.04 }
        runs-on: ${{ matrix.os }}
        steps:
          - name: '🧰 Checkout'
            uses: actions/checkout@v3
            with:
              fetch-depth: 0

          - name: Set up Python 3.10
            uses: actions/setup-python@v4
            with:
              python-version: '3.10'

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install pytest
          
          - name: Run tests
            run: pytest

    macos:
        strategy:
            fail-fast: false
            matrix:
                include:
                  - { os: macos-12  }
                  - { os: macos-11  }
        runs-on: ${{ matrix.os }}
        steps:
          - name: '🧰 Checkout'
            uses: actions/checkout@v3
            with:
              fetch-depth: 0

          - name: Set up Python 3.10
            uses: actions/setup-python@v4
            with:
              python-version: '3.10'

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install pytest
          
          - name: Run tests
            run: pytest

    windows:
        runs-on: windows-latest
        defaults:
            run:
                shell: msys2 {0}
        steps:
          - name: 'Setup MSYS2'
            uses: msys2/setup-msys2@v2
            with:
              msystem: mingw64
              update: true
              install: >-
                mingw-w64-x86_64-cmake
                mingw-w64-x86_64-ninja
                mingw-w64-x86_64-gcc-fortran
              path-type: inherit

          - name: '🧰 Checkout'
            uses: actions/checkout@v3
            with:
              fetch-depth: 0

          - name: Set up Python 3.10
            uses: actions/setup-python@v4
            with:
              python-version: '3.10'

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              python -m pip install pytest
          
          - name: Run tests
            run: pytest
            env:
              CMAKE_GENERATOR: Ninja
            timeout-minutes: 7