name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    name: Release bundled executables
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            CMD_BUILD: >
              pyinstaller --onefile --console -n secretshare secret.py &&
              cd dist/ &&
              zip secretshare-darwin-amd64-${{ env.RELEASE_VERSION }}.zip secretshare
            OUT_FILE_NAME: secretshare-darwin-amd64-${{ env.RELEASE_VERSION }}.zip
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: >
              pyinstaller --onefile --console -n secretshare secret.py &&
              cd dist/ &&
              7z a secretshare-windows-amd64-${{ env.RELEASE_VERSION }}.zip secretshare.exe
            OUT_FILE_NAME: secretshare-windows-amd64-${{ env.RELEASE_VERSION }}.zip 
    runs-on: ${{ matrix.os }}
            
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pytest
      
      - name: Run tests
        run: pytest

      - name: Build with pyinstaller for ${{matrix.TARGET}}
        run: ${{matrix.CMD_BUILD}}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: frankhinek/action-gh-release@d4e8205d7e959a9107da6396278b2f1f07af0f9b
        with:
          files: ./dist/${{ matrix.OUT_FILE_NAME}}